version: "2"

services:
  tarantool:
      build: src
      container_name: mytarantool
      ports:
        - 3301:3301
        - 8000:8000
      volumes:
        - .tarantool-data:/var/lib/tarantool
  nginx:
    build: nginx
    ports:
      - 80:80
